package org.example.enums;

public enum TelegramState {
    SHARE_CONTACT,
    CHECH_SUBSCRIBES,
    VOTE_USER,
    WAS_ANNOUNCED,
    ENTER_TEACHER_NAME,
    ADD_TO_LIST,
    CHECK_ADD_TO_LIST,
    START,
    ENTER_SCHOOL_NAME,
    NEW_KONKURS,
    TEXT,
    ADD_TEXT_TO_LIST,
    ADD_PHOTO_TO_LIST,
    SEND_A_PHOTO,
    STARTED_THE_BOT, STOPPED_THE_BOT
}
